### PR TITLE
Add support for cookies

### PR DESCRIPTION
**Pull request by imefisto**
## Description

Added support for cookies

## Motivation and context

Currently, there are no support for cookies.

## How has this been tested?

Added cover test for this feature.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [ x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [ ] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [ ] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by imefisto** [comment]
Added support for cookies

**Comment by pachico** [comment]
@imefisto , thanks for the great work!
It seems Travis pipeline is broken due to PEAR inactivity.
Let me come back to you as soon as I figure out what happened.

Thanks!

**Comment by pachico** [comment]
@imefisto Can you pull again from latest master? The pipeline should now work as expected.
Thanks!

**Comment by imefisto** [comment]
Hi @pachico , Trying again ..

**Pull request closed without merging**
